name: Check Format

on: pull_request

jobs:
  check_format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.14]
        otp: [24]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/set-up@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-format-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}-{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-format-cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Check Format
        run: mix format --check-formatted